/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomepageRouteImport } from './routes/_homepage'
import { Route as HomepageIndexRouteImport } from './routes/_homepage/index'
import { Route as GameGameIdRouteImport } from './routes/game/$gameId'
import { Route as HomepageRulesAndTermsRouteImport } from './routes/_homepage/rulesAndTerms'
import { Route as HomepageRegisterRouteImport } from './routes/_homepage/register'
import { Route as HomepageLoginRouteImport } from './routes/_homepage/login'
import { Route as HomepageFaqRouteImport } from './routes/_homepage/faq'
import { Route as HomepageDepositRouteImport } from './routes/_homepage/deposit'
import { Route as HomepageInstructionsInstructionRouteImport } from './routes/_homepage/instructions/$instruction'

const HomepageRoute = HomepageRouteImport.update({
  id: '/_homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageIndexRoute = HomepageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomepageRoute,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRulesAndTermsRoute = HomepageRulesAndTermsRouteImport.update({
  id: '/rulesAndTerms',
  path: '/rulesAndTerms',
  getParentRoute: () => HomepageRoute,
} as any)
const HomepageRegisterRoute = HomepageRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => HomepageRoute,
} as any)
const HomepageLoginRoute = HomepageLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HomepageRoute,
} as any)
const HomepageFaqRoute = HomepageFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => HomepageRoute,
} as any)
const HomepageDepositRoute = HomepageDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => HomepageRoute,
} as any)
const HomepageInstructionsInstructionRoute =
  HomepageInstructionsInstructionRouteImport.update({
    id: '/instructions/$instruction',
    path: '/instructions/$instruction',
    getParentRoute: () => HomepageRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/deposit': typeof HomepageDepositRoute
  '/faq': typeof HomepageFaqRoute
  '/login': typeof HomepageLoginRoute
  '/register': typeof HomepageRegisterRoute
  '/rulesAndTerms': typeof HomepageRulesAndTermsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/': typeof HomepageIndexRoute
  '/instructions/$instruction': typeof HomepageInstructionsInstructionRoute
}
export interface FileRoutesByTo {
  '/deposit': typeof HomepageDepositRoute
  '/faq': typeof HomepageFaqRoute
  '/login': typeof HomepageLoginRoute
  '/register': typeof HomepageRegisterRoute
  '/rulesAndTerms': typeof HomepageRulesAndTermsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/': typeof HomepageIndexRoute
  '/instructions/$instruction': typeof HomepageInstructionsInstructionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_homepage': typeof HomepageRouteWithChildren
  '/_homepage/deposit': typeof HomepageDepositRoute
  '/_homepage/faq': typeof HomepageFaqRoute
  '/_homepage/login': typeof HomepageLoginRoute
  '/_homepage/register': typeof HomepageRegisterRoute
  '/_homepage/rulesAndTerms': typeof HomepageRulesAndTermsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/_homepage/': typeof HomepageIndexRoute
  '/_homepage/instructions/$instruction': typeof HomepageInstructionsInstructionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/deposit'
    | '/faq'
    | '/login'
    | '/register'
    | '/rulesAndTerms'
    | '/game/$gameId'
    | '/'
    | '/instructions/$instruction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/deposit'
    | '/faq'
    | '/login'
    | '/register'
    | '/rulesAndTerms'
    | '/game/$gameId'
    | '/'
    | '/instructions/$instruction'
  id:
    | '__root__'
    | '/_homepage'
    | '/_homepage/deposit'
    | '/_homepage/faq'
    | '/_homepage/login'
    | '/_homepage/register'
    | '/_homepage/rulesAndTerms'
    | '/game/$gameId'
    | '/_homepage/'
    | '/_homepage/instructions/$instruction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomepageRoute: typeof HomepageRouteWithChildren
  GameGameIdRoute: typeof GameGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homepage': {
      id: '/_homepage'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homepage/': {
      id: '/_homepage/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomepageIndexRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homepage/rulesAndTerms': {
      id: '/_homepage/rulesAndTerms'
      path: '/rulesAndTerms'
      fullPath: '/rulesAndTerms'
      preLoaderRoute: typeof HomepageRulesAndTermsRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/_homepage/register': {
      id: '/_homepage/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof HomepageRegisterRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/_homepage/login': {
      id: '/_homepage/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof HomepageLoginRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/_homepage/faq': {
      id: '/_homepage/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof HomepageFaqRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/_homepage/deposit': {
      id: '/_homepage/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof HomepageDepositRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/_homepage/instructions/$instruction': {
      id: '/_homepage/instructions/$instruction'
      path: '/instructions/$instruction'
      fullPath: '/instructions/$instruction'
      preLoaderRoute: typeof HomepageInstructionsInstructionRouteImport
      parentRoute: typeof HomepageRoute
    }
  }
}

interface HomepageRouteChildren {
  HomepageDepositRoute: typeof HomepageDepositRoute
  HomepageFaqRoute: typeof HomepageFaqRoute
  HomepageLoginRoute: typeof HomepageLoginRoute
  HomepageRegisterRoute: typeof HomepageRegisterRoute
  HomepageRulesAndTermsRoute: typeof HomepageRulesAndTermsRoute
  HomepageIndexRoute: typeof HomepageIndexRoute
  HomepageInstructionsInstructionRoute: typeof HomepageInstructionsInstructionRoute
}

const HomepageRouteChildren: HomepageRouteChildren = {
  HomepageDepositRoute: HomepageDepositRoute,
  HomepageFaqRoute: HomepageFaqRoute,
  HomepageLoginRoute: HomepageLoginRoute,
  HomepageRegisterRoute: HomepageRegisterRoute,
  HomepageRulesAndTermsRoute: HomepageRulesAndTermsRoute,
  HomepageIndexRoute: HomepageIndexRoute,
  HomepageInstructionsInstructionRoute: HomepageInstructionsInstructionRoute,
}

const HomepageRouteWithChildren = HomepageRoute._addFileChildren(
  HomepageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomepageRoute: HomepageRouteWithChildren,
  GameGameIdRoute: GameGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
