/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomepageImport } from './routes/_homepage'
import { Route as HomepageIndexImport } from './routes/_homepage/index'
import { Route as GameGameIdImport } from './routes/game/$gameId'
import { Route as HomepageRulesAndTermsImport } from './routes/_homepage/rulesAndTerms'
import { Route as HomepageRegisterImport } from './routes/_homepage/register'
import { Route as HomepageLoginImport } from './routes/_homepage/login'
import { Route as HomepageFaqImport } from './routes/_homepage/faq'
import { Route as HomepageDepositImport } from './routes/_homepage/deposit'
import { Route as HomepageInstructionsInstructionImport } from './routes/_homepage/instructions/$instruction'

// Create/Update Routes

const HomepageRoute = HomepageImport.update({
  id: '/_homepage',
  getParentRoute: () => rootRoute,
} as any)

const HomepageIndexRoute = HomepageIndexImport.update({
  path: '/',
  getParentRoute: () => HomepageRoute,
} as any)

const GameGameIdRoute = GameGameIdImport.update({
  path: '/game/$gameId',
  getParentRoute: () => rootRoute,
} as any)

const HomepageRulesAndTermsRoute = HomepageRulesAndTermsImport.update({
  path: '/rulesAndTerms',
  getParentRoute: () => HomepageRoute,
} as any)

const HomepageRegisterRoute = HomepageRegisterImport.update({
  path: '/register',
  getParentRoute: () => HomepageRoute,
} as any)

const HomepageLoginRoute = HomepageLoginImport.update({
  path: '/login',
  getParentRoute: () => HomepageRoute,
} as any)

const HomepageFaqRoute = HomepageFaqImport.update({
  path: '/faq',
  getParentRoute: () => HomepageRoute,
} as any)

const HomepageDepositRoute = HomepageDepositImport.update({
  path: '/deposit',
  getParentRoute: () => HomepageRoute,
} as any)

const HomepageInstructionsInstructionRoute =
  HomepageInstructionsInstructionImport.update({
    path: '/instructions/$instruction',
    getParentRoute: () => HomepageRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_homepage': {
      id: '/_homepage'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomepageImport
      parentRoute: typeof rootRoute
    }
    '/_homepage/deposit': {
      id: '/_homepage/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof HomepageDepositImport
      parentRoute: typeof HomepageImport
    }
    '/_homepage/faq': {
      id: '/_homepage/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof HomepageFaqImport
      parentRoute: typeof HomepageImport
    }
    '/_homepage/login': {
      id: '/_homepage/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof HomepageLoginImport
      parentRoute: typeof HomepageImport
    }
    '/_homepage/register': {
      id: '/_homepage/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof HomepageRegisterImport
      parentRoute: typeof HomepageImport
    }
    '/_homepage/rulesAndTerms': {
      id: '/_homepage/rulesAndTerms'
      path: '/rulesAndTerms'
      fullPath: '/rulesAndTerms'
      preLoaderRoute: typeof HomepageRulesAndTermsImport
      parentRoute: typeof HomepageImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdImport
      parentRoute: typeof rootRoute
    }
    '/_homepage/': {
      id: '/_homepage/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomepageIndexImport
      parentRoute: typeof HomepageImport
    }
    '/_homepage/instructions/$instruction': {
      id: '/_homepage/instructions/$instruction'
      path: '/instructions/$instruction'
      fullPath: '/instructions/$instruction'
      preLoaderRoute: typeof HomepageInstructionsInstructionImport
      parentRoute: typeof HomepageImport
    }
  }
}

// Create and export the route tree

interface HomepageRouteChildren {
  HomepageDepositRoute: typeof HomepageDepositRoute
  HomepageFaqRoute: typeof HomepageFaqRoute
  HomepageLoginRoute: typeof HomepageLoginRoute
  HomepageRegisterRoute: typeof HomepageRegisterRoute
  HomepageRulesAndTermsRoute: typeof HomepageRulesAndTermsRoute
  HomepageIndexRoute: typeof HomepageIndexRoute
  HomepageInstructionsInstructionRoute: typeof HomepageInstructionsInstructionRoute
}

const HomepageRouteChildren: HomepageRouteChildren = {
  HomepageDepositRoute: HomepageDepositRoute,
  HomepageFaqRoute: HomepageFaqRoute,
  HomepageLoginRoute: HomepageLoginRoute,
  HomepageRegisterRoute: HomepageRegisterRoute,
  HomepageRulesAndTermsRoute: HomepageRulesAndTermsRoute,
  HomepageIndexRoute: HomepageIndexRoute,
  HomepageInstructionsInstructionRoute: HomepageInstructionsInstructionRoute,
}

const HomepageRouteWithChildren = HomepageRoute._addFileChildren(
  HomepageRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof HomepageRouteWithChildren
  '/deposit': typeof HomepageDepositRoute
  '/faq': typeof HomepageFaqRoute
  '/login': typeof HomepageLoginRoute
  '/register': typeof HomepageRegisterRoute
  '/rulesAndTerms': typeof HomepageRulesAndTermsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/': typeof HomepageIndexRoute
  '/instructions/$instruction': typeof HomepageInstructionsInstructionRoute
}

export interface FileRoutesByTo {
  '/deposit': typeof HomepageDepositRoute
  '/faq': typeof HomepageFaqRoute
  '/login': typeof HomepageLoginRoute
  '/register': typeof HomepageRegisterRoute
  '/rulesAndTerms': typeof HomepageRulesAndTermsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/': typeof HomepageIndexRoute
  '/instructions/$instruction': typeof HomepageInstructionsInstructionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_homepage': typeof HomepageRouteWithChildren
  '/_homepage/deposit': typeof HomepageDepositRoute
  '/_homepage/faq': typeof HomepageFaqRoute
  '/_homepage/login': typeof HomepageLoginRoute
  '/_homepage/register': typeof HomepageRegisterRoute
  '/_homepage/rulesAndTerms': typeof HomepageRulesAndTermsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/_homepage/': typeof HomepageIndexRoute
  '/_homepage/instructions/$instruction': typeof HomepageInstructionsInstructionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/deposit'
    | '/faq'
    | '/login'
    | '/register'
    | '/rulesAndTerms'
    | '/game/$gameId'
    | '/'
    | '/instructions/$instruction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/deposit'
    | '/faq'
    | '/login'
    | '/register'
    | '/rulesAndTerms'
    | '/game/$gameId'
    | '/'
    | '/instructions/$instruction'
  id:
    | '__root__'
    | '/_homepage'
    | '/_homepage/deposit'
    | '/_homepage/faq'
    | '/_homepage/login'
    | '/_homepage/register'
    | '/_homepage/rulesAndTerms'
    | '/game/$gameId'
    | '/_homepage/'
    | '/_homepage/instructions/$instruction'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomepageRoute: typeof HomepageRouteWithChildren
  GameGameIdRoute: typeof GameGameIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomepageRoute: HomepageRouteWithChildren,
  GameGameIdRoute: GameGameIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_homepage",
        "/game/$gameId"
      ]
    },
    "/_homepage": {
      "filePath": "_homepage.tsx",
      "children": [
        "/_homepage/deposit",
        "/_homepage/faq",
        "/_homepage/login",
        "/_homepage/register",
        "/_homepage/rulesAndTerms",
        "/_homepage/",
        "/_homepage/instructions/$instruction"
      ]
    },
    "/_homepage/deposit": {
      "filePath": "_homepage/deposit.tsx",
      "parent": "/_homepage"
    },
    "/_homepage/faq": {
      "filePath": "_homepage/faq.tsx",
      "parent": "/_homepage"
    },
    "/_homepage/login": {
      "filePath": "_homepage/login.tsx",
      "parent": "/_homepage"
    },
    "/_homepage/register": {
      "filePath": "_homepage/register.tsx",
      "parent": "/_homepage"
    },
    "/_homepage/rulesAndTerms": {
      "filePath": "_homepage/rulesAndTerms.tsx",
      "parent": "/_homepage"
    },
    "/game/$gameId": {
      "filePath": "game/$gameId.tsx"
    },
    "/_homepage/": {
      "filePath": "_homepage/index.tsx",
      "parent": "/_homepage"
    },
    "/_homepage/instructions/$instruction": {
      "filePath": "_homepage/instructions/$instruction.tsx",
      "parent": "/_homepage"
    }
  }
}
ROUTE_MANIFEST_END */
